{
    'name': 'Lubricant Flow',
    'version': '20.0.2.0.0',
    'category': 'Inventory/Purchase',
    'summary': "Importation et vente de lubrifiants",
    'depends': ['purchase', 'sale_management', 'stock', 'account'],
    'data': [
        'security/ir.access.csv',
        'data/sequences.xml',
        'data/doc_types.xml',
        'data/home_cards.xml',
        'views/import_views.xml',
        'views/vat_certificate_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/home_views.xml',
        'views/history_views.xml',
        'views/menus.xml',
        'report/lubricant_reports.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
